### ISSUE TITLE
onMouseMove is not stopped adequately when not explicitly "checking".

### ISSUE THREAD

**Issue by CakeCrusher** [baptisteArno/tinking#12]
**Describe the bug**
The `onMouseMove` is not stopped in any way other than confirming the selection, yet confirming the selection is not obligated. 

**To Reproduce**
1. Go to 'https://www.youtube.com/'
2. Extract title text from a video (do not confirm)
3. Add another step
4. See error (reguardless of what you do in the next step you continue editing the previous step)

**Expected behavior**
When you don't "check" of a step and move on to something else the `onMouseMove` should stop.

**Additional context**
Either make the "check" obligated (cant do anything else untill its confirmed) or BETTER yet make it so that whenever any other step is in focus automatically confirm and stop `onMouseMove`.

**Comment by CakeCrusher** [comment]
Reset button also does not affect the onMouseMove, leading to more issues.

**Comment by baptisteArno** [comment]
Sorry, I wanted to create a PR but I made a mistake and I directly pushed to master. You can view the commit that close this issue [here](https://github.com/baptisteArno/tinking/commit/245f95a05550d398b795b2f2b35da8a8016f99ea)
