### ISSUE TITLE
When starting onMouseMove and then page is reset the step no longer works.

### ISSUE THREAD

**Issue by CakeCrusher** [baptisteArno/tinking#13]
**Describe the bug**
When in the process of selecting a node, if the page is reset, that node becomes useless unless you select a different action.

**To Reproduce**
1. Go to 'https://www.youtube.com/'
2. Add step with action to extract text
3. Reload window
4. See error (step does not work)

**Expected behavior**
The step should be activated again when window is reloaded

**Additional context**
I suggest that it should be fixed by deleting the in-progress step altogether when page is reloaded.

**Comment by baptisteArno** [comment]
Looks like it works now! 👍
