### ISSUE TITLE
Step being worked on should be highlighted.

### ISSUE THREAD

**Issue by CakeCrusher** [baptisteArno/tinking#14]
**Is your feature request related to a problem? Please describe.**
It is related to the "without explicit "checking"" issue.

**Describe the solution you'd like**
Make it clear which step you are working on at the moment.

**Describe alternatives you've considered**
Reduce opacity for steps that are not currently being worked on.

**Additional context**

**Comment by baptisteArno** [comment]
Yes, great idea. I'll work on it 💪
