### ISSUE TITLE
"record clicks and keys" does not work when previous action was not explicitly "checked".

### ISSUE THREAD

**Issue by CakeCrusher** [baptisteArno/tinking#18]
**Describe the bug**
Related to issue #12 

**To Reproduce**
1. Go to 'https://www.youtube.com/'
2. Make step to extract text
3. Click on video title (do not "check")
4. Make step to "record..."
4. See error (overlay still active)

**Expected behavior**
Overlay to disappear and "record..." action to begin.

**Additional context**
This issue is also related to the unclear focus of what step you are on. Whenever I click on new step I would expect that new step to be the focus therefore the overlay should disappear.

**Comment by CakeCrusher** [comment]
I think the "focus step" concept should be deeply integrated into the step functionality so as it could fix a ton of errors.

**Comment by baptisteArno** [comment]
Have you pulled the last changes on master? I'm pretty sure the latest modifications fix this behavior
