### ISSUE TITLE
Can't resolve dependencies

### ISSUE THREAD

**Issue by geotrev** [baptisteArno/tinking#3]
Hello! I'm setting up the project to give it a test go. I'm running into a dependency tree issue when running `npm i`:

```sh
npm ERR! While resolving: tinking@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!   peer react@"16.x || 17.x" from @chakra-ui/react@1.0.1
npm ERR!   node_modules/@chakra-ui/react
npm ERR!     @chakra-ui/react@"^1.0.1" from the root project
npm ERR!   2 more (@emotion/react, @emotion/styled)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8" from framer-motion@2.9.4
npm ERR! node_modules/framer-motion
npm ERR!   framer-motion@"^2.9.4" from the root project
npm ERR!   peer framer-motion@"^2.9.4" from @chakra-ui/react@1.0.1
npm ERR!   node_modules/@chakra-ui/react
npm ERR!     @chakra-ui/react@"^1.0.1" from the root project
```

I'm running node 14.7.0 and npm 7.5.2. 

Not sure why it's complaining here - your version of `react` seems to be compatible with `framer-motion` and `@chakra-ui/react`. 🤷‍♂️

**Comment by joealden** [comment]
1. `framer-motion@2.9.4` doesn't explicitly support React 17 (this was done in `framer-motion@2.9.5`). This is why NPM is complaining.
2. As this project contains a `yarn.lock` file, its probably wise to install the deps via yarn (v1).

**Comment by geotrev** [comment]
ah word. i'll do that. cheers.

**Comment by baptisteArno** [comment]
Thank you for submitting this issue. We need to commit a `package-lock.json` 👍
