### ISSUE TITLE
need user feedback conveniently on the popup

### ISSUE THREAD

**Issue by CakeCrusher** [baptisteArno/tinking#31]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Some component at the bottom of the popup that is dynamic and reacts according to the most probable issue. If the user generated code; the feedback should be set to a code broblem mode. If the user is in the middle of scraping; the feedback should be set to a scraping mode.

**Describe alternatives you've considered**

**Additional context**
The solution I suggest is very y complex but we don't really need that. But we Tinking definitely NEEDS user feedback

**Comment by baptisteArno** [comment]
I'll work into adding tooltips on everything 👍

**Comment by baptisteArno** [comment]
Closing this since it is not specific enough. Now the tool isn't buggy
